name: LushCore
author: QuickScythe
version: 0.0.1
description: Announcement Core for LushMC
api-version: 1.15
api: Spigot
depend: PlaceholderAPI
main: net.lushmc.core.LushPlugin
commands:
   lush:
      usage: /lush
   console:
      usage: /console