name: LushCore
author: QuickScythe
version: 0.0.2
description: Core for LushMC
api-version: 1.15
api: Spigot
depend:
- PlaceholderAPI
main: net.lushmc.core.LushPlugin
commands:
   lush:
      usage: /lush
   console:
      usage: /console
   debug:
      usage: /debug
   update:
      usage: /update [plugin] [in-dev|(true/false)]